//
// mimixbox/internal/applets/shellutils/ghrdc/ghrdc.go
//
// Copyright 2021 Naohiro CHIKAMATSU
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package ghrdc implements the ghrdc applet: GitHub Release Download Counter.
// It queries the GitHub releases API for a repository and prints the number of
// downloads per release asset (binary vs. source code).
package ghrdc

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/nao1215/mimixbox/internal/command"
)

// apiBaseURL is the GitHub releases API endpoint prefix. It is a package
// variable so tests can point it at an httptest server instead of the real
// network. The repository "USER/REPOSITORY" and "/releases" are appended.
var apiBaseURL = "https://api.github.com/repos/"

// SetAPIBaseURL overrides the GitHub API base URL and returns a function that
// restores the previous value. It exists so tests can redirect requests to an
// httptest server without touching the real network.
func SetAPIBaseURL(url string) (restore func()) {
	prev := apiBaseURL
	apiBaseURL = url
	return func() { apiBaseURL = prev }
}

// Command is the ghrdc applet.
type Command struct{}

// New returns a ghrdc command.
func New() *Command { return &Command{} }

// Name returns the command name.
func (c *Command) Name() string { return "ghrdc" }

// Synopsis returns the one-line description shown in the applet list.
func (c *Command) Synopsis() string { return "GitHub Relase Download Counter" }

type options struct {
	all   bool
	total bool
}

// GitHubReleaseData is a structure for receiving GitHub Release information in json format.
// The following structure was generated by JSON-to-GO.
// JSON-to-GO: https://mholt.github.io/json-to-go/
type GitHubReleaseData struct {
	URL       string `json:"url"`
	AssetsURL string `json:"assets_url"`
	UploadURL string `json:"upload_url"`
	HTMLURL   string `json:"html_url"`
	ID        int    `json:"id"`
	Author    struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"author"`
	NodeID          string    `json:"node_id"`
	TagName         string    `json:"tag_name"`
	TargetCommitish string    `json:"target_commitish"`
	Name            string    `json:"name"`
	Draft           bool      `json:"draft"`
	Prerelease      bool      `json:"prerelease"`
	CreatedAt       time.Time `json:"created_at"`
	PublishedAt     time.Time `json:"published_at"`
	Assets          []struct {
		URL      string `json:"url"`
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		Label    any    `json:"label"`
		Uploader struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"uploader"`
		ContentType        string    `json:"content_type"`
		State              string    `json:"state"`
		Size               int       `json:"size"`
		DownloadCount      int       `json:"download_count"`
		CreatedAt          time.Time `json:"created_at"`
		UpdatedAt          time.Time `json:"updated_at"`
		BrowserDownloadURL string    `json:"browser_download_url"`
	} `json:"assets"`
	TarballURL string `json:"tarball_url"`
	ZipballURL string `json:"zipball_url"`
	Body       string `json:"body"`
}

// Run executes ghrdc.
func (c *Command) Run(ctx context.Context, stdio command.IO, args []string) error {
	fs := command.NewFlagSet(c.Name(), "[OPTION]... USER/REPOSITORY", stdio.Err)
	all := fs.BoolP("all", "a", false, "Show total number of downloads per release")
	total := fs.BoolP("total", "t", false, "Show total number of downloads for all releases")

	proceed, err := fs.Parse(stdio, args)
	if err != nil || !proceed {
		return err
	}

	operands := fs.Args()
	switch {
	case len(operands) == 0:
		_, _ = fmt.Fprintf(stdio.Err, "%s: missing operand: specify USER/REPOSITORY\n", c.Name())
		_, _ = fmt.Fprintf(stdio.Err, "Try '%s --help' for more information.\n", c.Name())
		return command.SilentFailure()
	case len(operands) > 1:
		_, _ = fmt.Fprintf(stdio.Err, "%s: extra operand '%s'\n", c.Name(), operands[1])
		_, _ = fmt.Fprintf(stdio.Err, "Try '%s --help' for more information.\n", c.Name())
		return command.SilentFailure()
	}
	repository := operands[0]

	data, err := fetchGitHubReleaseData(ctx, repository)
	if err != nil {
		_, _ = fmt.Fprintf(stdio.Err, "%s: %v\n", c.Name(), err)
		return command.SilentFailure()
	}
	if len(data) == 0 {
		// Because the ghrdc command does not authenticate with GitHub API,
		// there are restrictions on the results that can be obtained.
		// There is the method to use the following library for API authentication.
		// (However, no plans to add functions).
		// URL: https://github.com/google/go-github
		_, _ = fmt.Fprintf(stdio.Err, "%s: Release Data is nothing. If %s is organization repository,\n"+
			"gdrdc commant can't get release data.\n", c.Name(), repository)
		return command.SilentFailure()
	}

	opts := options{all: *all, total: *total}
	render(stdio.Out, data, opts)
	return nil
}

// render formats the download counts for data according to opts and writes the
// result to w. It preserves the exact layout of the original implementation.
func render(w io.Writer, data []GitHubReleaseData, opts options) {
	var totalSrcCnt int
	var totalBinCnt int
	for i, d := range data {
		srcCnt, binCnt := calcTotalDownloadCount(d)
		totalSrcCnt += srcCnt
		totalBinCnt += binCnt

		if !opts.total {
			_, _ = fmt.Fprintf(w, "[Name(Version)]             :%s\n", d.Name)
			_, _ = fmt.Fprintf(w, "[Release Date]              :%s\n", d.PublishedAt)
			_, _ = fmt.Fprintf(w, "[Binary Download Count]     :%d\n", binCnt)
			_, _ = fmt.Fprintf(w, "[Source Code Download Count]:%d\n", srcCnt)
		}
		// In the default case, the latest result is displayed.
		if !opts.all && !opts.total {
			break
		}

		// Adjust line feed between results. If last result, not add line feed.
		if (i+1) != len(data) && !opts.total {
			_, _ = fmt.Fprintln(w, "")
		}
	}

	if opts.total {
		_, _ = fmt.Fprintf(w, "[Name(Version)]                    :All release\n")
		_, _ = fmt.Fprintf(w, "[Release Date]                     :-\n")
		_, _ = fmt.Fprintf(w, "[Binary Download Count(total)]     :%d\n", totalBinCnt)
		_, _ = fmt.Fprintf(w, "[Source Code Download Count(total)]:%d\n", totalSrcCnt)
	}
}

// fetchGitHubReleaseData runs the GitHub Web API for repositoryName
// ("USER/REPOSITORY") and converts the acquired json to a slice of structures.
func fetchGitHubReleaseData(ctx context.Context, repositoryName string) ([]GitHubReleaseData, error) {
	endpoint := apiBaseURL + repositoryName + "/releases"

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("can't build request for GitHub: %w", err)
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("can't get response from GitHub: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("can't read response from GitHub: %w", err)
	}

	var data []GitHubReleaseData
	if err := json.Unmarshal(body, &data); err != nil {
		return nil, fmt.Errorf("can't convert json to structure data. Is the repository name correct?: %w", err)
	}
	return data, nil
}

// calcTotalDownloadCount calculates the number of downloads (total value) of
// executable files and source code for a single release.
func calcTotalDownloadCount(ghrd GitHubReleaseData) (int, int) {
	var srcCnt int
	var binCnt int
	for _, asset := range ghrd.Assets {
		if isSourceCodeFileURL(asset.BrowserDownloadURL) {
			srcCnt += asset.DownloadCount
		} else {
			binCnt += asset.DownloadCount
		}
	}
	return srcCnt, binCnt
}

// isSourceCodeFileURL parses the URL and guesses if the target file(URL) is source code.
func isSourceCodeFileURL(str string) bool {
	likelySrcCode := []string{"src", "Src", "SRC", "source", "Source"}

	for _, target := range likelySrcCode {
		if strings.Contains(str, target) {
			return true
		}
	}
	return false
}
