// Code generated by "go generate"; DO NOT EDIT.
//
// Run `make generate` (or `go generate ./...`) after adding or removing an
// applet package to regenerate the registry.
package applets

import (
	ap_archival_ar "github.com/nao1215/mimixbox/internal/applets/archival/ar"
	ap_archival_bunzip2 "github.com/nao1215/mimixbox/internal/applets/archival/bunzip2"
	ap_archival_compress "github.com/nao1215/mimixbox/internal/applets/archival/compress"
	ap_archival_cpio "github.com/nao1215/mimixbox/internal/applets/archival/cpio"
	ap_archival_gunzip "github.com/nao1215/mimixbox/internal/applets/archival/gunzip"
	ap_archival_gzip "github.com/nao1215/mimixbox/internal/applets/archival/gzip"
	ap_archival_pipeprogress "github.com/nao1215/mimixbox/internal/applets/archival/pipeprogress"
	ap_archival_rpm "github.com/nao1215/mimixbox/internal/applets/archival/rpm"
	ap_archival_rpm2cpio "github.com/nao1215/mimixbox/internal/applets/archival/rpm2cpio"
	ap_archival_tar "github.com/nao1215/mimixbox/internal/applets/archival/tar"
	ap_archival_uncompress "github.com/nao1215/mimixbox/internal/applets/archival/uncompress"
	ap_archival_unzip "github.com/nao1215/mimixbox/internal/applets/archival/unzip"
	ap_archival_xzcomp "github.com/nao1215/mimixbox/internal/applets/archival/xzcomp"
	ap_archival_zip "github.com/nao1215/mimixbox/internal/applets/archival/zip"
	ap_compat_bracket "github.com/nao1215/mimixbox/internal/applets/compat/bracket"
	ap_compat_busybox "github.com/nao1215/mimixbox/internal/applets/compat/busybox"
	ap_compat_cttyhack "github.com/nao1215/mimixbox/internal/applets/compat/cttyhack"
	ap_compat_shellfront "github.com/nao1215/mimixbox/internal/applets/compat/shellfront"
	ap_compat_unit "github.com/nao1215/mimixbox/internal/applets/compat/unit"
	ap_console_tools_clear "github.com/nao1215/mimixbox/internal/applets/console-tools/clear"
	ap_console_tools_pager "github.com/nao1215/mimixbox/internal/applets/console-tools/pager"
	ap_console_tools_reset "github.com/nao1215/mimixbox/internal/applets/console-tools/reset"
	ap_console_tools_resize "github.com/nao1215/mimixbox/internal/applets/console-tools/resize"
	ap_console_tools_stty "github.com/nao1215/mimixbox/internal/applets/console-tools/stty"
	ap_debianutils_add_shell "github.com/nao1215/mimixbox/internal/applets/debianutils/add-shell"
	ap_debianutils_ischroot "github.com/nao1215/mimixbox/internal/applets/debianutils/ischroot"
	ap_debianutils_mktemp "github.com/nao1215/mimixbox/internal/applets/debianutils/mktemp"
	ap_debianutils_remove_shell "github.com/nao1215/mimixbox/internal/applets/debianutils/remove-shell"
	ap_debianutils_valid_shell "github.com/nao1215/mimixbox/internal/applets/debianutils/valid-shell"
	ap_debianutils_which "github.com/nao1215/mimixbox/internal/applets/debianutils/which"
	ap_editors_awk "github.com/nao1215/mimixbox/internal/applets/editors/awk"
	ap_editors_diff "github.com/nao1215/mimixbox/internal/applets/editors/diff"
	ap_editors_ed "github.com/nao1215/mimixbox/internal/applets/editors/ed"
	ap_editors_patch "github.com/nao1215/mimixbox/internal/applets/editors/patch"
	ap_editors_sed "github.com/nao1215/mimixbox/internal/applets/editors/sed"
	ap_editors_vi "github.com/nao1215/mimixbox/internal/applets/editors/vi"
	ap_fileutils_chgrp "github.com/nao1215/mimixbox/internal/applets/fileutils/chgrp"
	ap_fileutils_chown "github.com/nao1215/mimixbox/internal/applets/fileutils/chown"
	ap_fileutils_cp "github.com/nao1215/mimixbox/internal/applets/fileutils/cp"
	ap_fileutils_link "github.com/nao1215/mimixbox/internal/applets/fileutils/link"
	ap_fileutils_ln "github.com/nao1215/mimixbox/internal/applets/fileutils/ln"
	ap_fileutils_ls "github.com/nao1215/mimixbox/internal/applets/fileutils/ls"
	ap_fileutils_mkdir "github.com/nao1215/mimixbox/internal/applets/fileutils/mkdir"
	ap_fileutils_mkfifo "github.com/nao1215/mimixbox/internal/applets/fileutils/mkfifo"
	ap_fileutils_mountpoint "github.com/nao1215/mimixbox/internal/applets/fileutils/mountpoint"
	ap_fileutils_mv "github.com/nao1215/mimixbox/internal/applets/fileutils/mv"
	ap_fileutils_readlink "github.com/nao1215/mimixbox/internal/applets/fileutils/readlink"
	ap_fileutils_rm "github.com/nao1215/mimixbox/internal/applets/fileutils/rm"
	ap_fileutils_rmdir "github.com/nao1215/mimixbox/internal/applets/fileutils/rmdir"
	ap_fileutils_shred "github.com/nao1215/mimixbox/internal/applets/fileutils/shred"
	ap_fileutils_stat "github.com/nao1215/mimixbox/internal/applets/fileutils/stat"
	ap_fileutils_touch "github.com/nao1215/mimixbox/internal/applets/fileutils/touch"
	ap_fileutils_truncate "github.com/nao1215/mimixbox/internal/applets/fileutils/truncate"
	ap_fileutils_unlink "github.com/nao1215/mimixbox/internal/applets/fileutils/unlink"
	ap_findutils_find "github.com/nao1215/mimixbox/internal/applets/findutils/find"
	ap_findutils_grep "github.com/nao1215/mimixbox/internal/applets/findutils/grep"
	ap_findutils_grepalias "github.com/nao1215/mimixbox/internal/applets/findutils/grepalias"
	ap_findutils_xargs "github.com/nao1215/mimixbox/internal/applets/findutils/xargs"
	ap_games_lifegame "github.com/nao1215/mimixbox/internal/applets/games/lifegame"
	ap_jokeutils_banner "github.com/nao1215/mimixbox/internal/applets/jokeutils/banner"
	ap_jokeutils_cmatrix "github.com/nao1215/mimixbox/internal/applets/jokeutils/cmatrix"
	ap_jokeutils_cowsay "github.com/nao1215/mimixbox/internal/applets/jokeutils/cowsay"
	ap_jokeutils_cowthink "github.com/nao1215/mimixbox/internal/applets/jokeutils/cowthink"
	ap_jokeutils_fakemovie "github.com/nao1215/mimixbox/internal/applets/jokeutils/fakemovie"
	ap_jokeutils_fortune "github.com/nao1215/mimixbox/internal/applets/jokeutils/fortune"
	ap_jokeutils_nyancat "github.com/nao1215/mimixbox/internal/applets/jokeutils/nyancat"
	ap_jokeutils_sl "github.com/nao1215/mimixbox/internal/applets/jokeutils/sl"
	ap_loginutils_acpid "github.com/nao1215/mimixbox/internal/applets/loginutils/acpid"
	ap_loginutils_addgroup "github.com/nao1215/mimixbox/internal/applets/loginutils/addgroup"
	ap_loginutils_adduser "github.com/nao1215/mimixbox/internal/applets/loginutils/adduser"
	ap_loginutils_bootchartd "github.com/nao1215/mimixbox/internal/applets/loginutils/bootchartd"
	ap_loginutils_chpasswd "github.com/nao1215/mimixbox/internal/applets/loginutils/chpasswd"
	ap_loginutils_crond "github.com/nao1215/mimixbox/internal/applets/loginutils/crond"
	ap_loginutils_crontab "github.com/nao1215/mimixbox/internal/applets/loginutils/crontab"
	ap_loginutils_cryptpw "github.com/nao1215/mimixbox/internal/applets/loginutils/cryptpw"
	ap_loginutils_delgroup "github.com/nao1215/mimixbox/internal/applets/loginutils/delgroup"
	ap_loginutils_deluser "github.com/nao1215/mimixbox/internal/applets/loginutils/deluser"
	ap_loginutils_getty "github.com/nao1215/mimixbox/internal/applets/loginutils/getty"
	ap_loginutils_init "github.com/nao1215/mimixbox/internal/applets/loginutils/init"
	ap_loginutils_login "github.com/nao1215/mimixbox/internal/applets/loginutils/login"
	ap_loginutils_mkpasswd "github.com/nao1215/mimixbox/internal/applets/loginutils/mkpasswd"
	ap_loginutils_nologin "github.com/nao1215/mimixbox/internal/applets/loginutils/nologin"
	ap_loginutils_passwd "github.com/nao1215/mimixbox/internal/applets/loginutils/passwd"
	ap_loginutils_runinit "github.com/nao1215/mimixbox/internal/applets/loginutils/runinit"
	ap_loginutils_runlevel "github.com/nao1215/mimixbox/internal/applets/loginutils/runlevel"
	ap_loginutils_runparts "github.com/nao1215/mimixbox/internal/applets/loginutils/runparts"
	ap_loginutils_startstopdaemon "github.com/nao1215/mimixbox/internal/applets/loginutils/startstopdaemon"
	ap_loginutils_su "github.com/nao1215/mimixbox/internal/applets/loginutils/su"
	ap_loginutils_sulogin "github.com/nao1215/mimixbox/internal/applets/loginutils/sulogin"
	ap_loginutils_vlock "github.com/nao1215/mimixbox/internal/applets/loginutils/vlock"
	ap_netutils_httpstatus "github.com/nao1215/mimixbox/internal/applets/netutils/httpstatus"
	ap_netutils_nc "github.com/nao1215/mimixbox/internal/applets/netutils/nc"
	ap_netutils_ping "github.com/nao1215/mimixbox/internal/applets/netutils/ping"
	ap_netutils_whris "github.com/nao1215/mimixbox/internal/applets/netutils/whris"
	ap_pmutils_halt "github.com/nao1215/mimixbox/internal/applets/pmutils/halt"
	ap_procps_fuser "github.com/nao1215/mimixbox/internal/applets/procps/fuser"
	ap_procps_iostat "github.com/nao1215/mimixbox/internal/applets/procps/iostat"
	ap_procps_killall5 "github.com/nao1215/mimixbox/internal/applets/procps/killall5"
	ap_procps_klogd "github.com/nao1215/mimixbox/internal/applets/procps/klogd"
	ap_procps_logger "github.com/nao1215/mimixbox/internal/applets/procps/logger"
	ap_procps_logread "github.com/nao1215/mimixbox/internal/applets/procps/logread"
	ap_procps_lsof "github.com/nao1215/mimixbox/internal/applets/procps/lsof"
	ap_procps_minips "github.com/nao1215/mimixbox/internal/applets/procps/minips"
	ap_procps_mpstat "github.com/nao1215/mimixbox/internal/applets/procps/mpstat"
	ap_procps_nmeter "github.com/nao1215/mimixbox/internal/applets/procps/nmeter"
	ap_procps_pgrep "github.com/nao1215/mimixbox/internal/applets/procps/pgrep"
	ap_procps_pmap "github.com/nao1215/mimixbox/internal/applets/procps/pmap"
	ap_procps_powertop "github.com/nao1215/mimixbox/internal/applets/procps/powertop"
	ap_procps_ps "github.com/nao1215/mimixbox/internal/applets/procps/ps"
	ap_procps_pstree "github.com/nao1215/mimixbox/internal/applets/procps/pstree"
	ap_procps_pwdx "github.com/nao1215/mimixbox/internal/applets/procps/pwdx"
	ap_procps_smemcap "github.com/nao1215/mimixbox/internal/applets/procps/smemcap"
	ap_procps_sysctl "github.com/nao1215/mimixbox/internal/applets/procps/sysctl"
	ap_procps_syslogd "github.com/nao1215/mimixbox/internal/applets/procps/syslogd"
	ap_procps_top "github.com/nao1215/mimixbox/internal/applets/procps/top"
	ap_procps_uptime "github.com/nao1215/mimixbox/internal/applets/procps/uptime"
	ap_procps_vmstat "github.com/nao1215/mimixbox/internal/applets/procps/vmstat"
	ap_runit_chpst "github.com/nao1215/mimixbox/internal/applets/runit/chpst"
	ap_runit_envdir "github.com/nao1215/mimixbox/internal/applets/runit/envdir"
	ap_runit_envuidgid "github.com/nao1215/mimixbox/internal/applets/runit/envuidgid"
	ap_runit_setuidgid "github.com/nao1215/mimixbox/internal/applets/runit/setuidgid"
	ap_runit_softlimit "github.com/nao1215/mimixbox/internal/applets/runit/softlimit"
	ap_runit_svlogd "github.com/nao1215/mimixbox/internal/applets/runit/svlogd"
	ap_runit_svok "github.com/nao1215/mimixbox/internal/applets/runit/svok"
	ap_securityutils_pwcrack "github.com/nao1215/mimixbox/internal/applets/securityutils/pwcrack"
	ap_securityutils_pwgen "github.com/nao1215/mimixbox/internal/applets/securityutils/pwgen"
	ap_securityutils_pwscore "github.com/nao1215/mimixbox/internal/applets/securityutils/pwscore"
	ap_securityutils_unshadow "github.com/nao1215/mimixbox/internal/applets/securityutils/unshadow"
	ap_securityutils_zippwcrack "github.com/nao1215/mimixbox/internal/applets/securityutils/zippwcrack"
	ap_shellutils_arch "github.com/nao1215/mimixbox/internal/applets/shellutils/arch"
	ap_shellutils_base64 "github.com/nao1215/mimixbox/internal/applets/shellutils/base64"
	ap_shellutils_basename "github.com/nao1215/mimixbox/internal/applets/shellutils/basename"
	ap_shellutils_bc "github.com/nao1215/mimixbox/internal/applets/shellutils/bc"
	ap_shellutils_cal "github.com/nao1215/mimixbox/internal/applets/shellutils/cal"
	ap_shellutils_chmod "github.com/nao1215/mimixbox/internal/applets/shellutils/chmod"
	ap_shellutils_chroot "github.com/nao1215/mimixbox/internal/applets/shellutils/chroot"
	ap_shellutils_cmp "github.com/nao1215/mimixbox/internal/applets/shellutils/cmp"
	ap_shellutils_cut "github.com/nao1215/mimixbox/internal/applets/shellutils/cut"
	ap_shellutils_date "github.com/nao1215/mimixbox/internal/applets/shellutils/date"
	ap_shellutils_dc "github.com/nao1215/mimixbox/internal/applets/shellutils/dc"
	ap_shellutils_dd "github.com/nao1215/mimixbox/internal/applets/shellutils/dd"
	ap_shellutils_df "github.com/nao1215/mimixbox/internal/applets/shellutils/df"
	ap_shellutils_dirname "github.com/nao1215/mimixbox/internal/applets/shellutils/dirname"
	ap_shellutils_du "github.com/nao1215/mimixbox/internal/applets/shellutils/du"
	ap_shellutils_echo "github.com/nao1215/mimixbox/internal/applets/shellutils/echo"
	ap_shellutils_env "github.com/nao1215/mimixbox/internal/applets/shellutils/env"
	ap_shellutils_expr "github.com/nao1215/mimixbox/internal/applets/shellutils/expr"
	ap_shellutils_factor "github.com/nao1215/mimixbox/internal/applets/shellutils/factor"
	ap_shellutils_false "github.com/nao1215/mimixbox/internal/applets/shellutils/false"
	ap_shellutils_free "github.com/nao1215/mimixbox/internal/applets/shellutils/free"
	ap_shellutils_fsync "github.com/nao1215/mimixbox/internal/applets/shellutils/fsync"
	ap_shellutils_ghrdc "github.com/nao1215/mimixbox/internal/applets/shellutils/ghrdc"
	ap_shellutils_groups "github.com/nao1215/mimixbox/internal/applets/shellutils/groups"
	ap_shellutils_hostid "github.com/nao1215/mimixbox/internal/applets/shellutils/hostid"
	ap_shellutils_hostname "github.com/nao1215/mimixbox/internal/applets/shellutils/hostname"
	ap_shellutils_id "github.com/nao1215/mimixbox/internal/applets/shellutils/id"
	ap_shellutils_install "github.com/nao1215/mimixbox/internal/applets/shellutils/install"
	ap_shellutils_kill "github.com/nao1215/mimixbox/internal/applets/shellutils/kill"
	ap_shellutils_killall "github.com/nao1215/mimixbox/internal/applets/shellutils/killall"
	ap_shellutils_logcollect "github.com/nao1215/mimixbox/internal/applets/shellutils/logcollect"
	ap_shellutils_logname "github.com/nao1215/mimixbox/internal/applets/shellutils/logname"
	ap_shellutils_mbsh "github.com/nao1215/mimixbox/internal/applets/shellutils/mbsh"
	ap_shellutils_mknod "github.com/nao1215/mimixbox/internal/applets/shellutils/mknod"
	ap_shellutils_nice "github.com/nao1215/mimixbox/internal/applets/shellutils/nice"
	ap_shellutils_nohup "github.com/nao1215/mimixbox/internal/applets/shellutils/nohup"
	ap_shellutils_nproc "github.com/nao1215/mimixbox/internal/applets/shellutils/nproc"
	ap_shellutils_od "github.com/nao1215/mimixbox/internal/applets/shellutils/od"
	ap_shellutils_path "github.com/nao1215/mimixbox/internal/applets/shellutils/path"
	ap_shellutils_pidof "github.com/nao1215/mimixbox/internal/applets/shellutils/pidof"
	ap_shellutils_posixer "github.com/nao1215/mimixbox/internal/applets/shellutils/posixer"
	ap_shellutils_printenv "github.com/nao1215/mimixbox/internal/applets/shellutils/printenv"
	ap_shellutils_printf "github.com/nao1215/mimixbox/internal/applets/shellutils/printf"
	ap_shellutils_pwd "github.com/nao1215/mimixbox/internal/applets/shellutils/pwd"
	ap_shellutils_realpath "github.com/nao1215/mimixbox/internal/applets/shellutils/realpath"
	ap_shellutils_sddf "github.com/nao1215/mimixbox/internal/applets/shellutils/sddf"
	ap_shellutils_seq "github.com/nao1215/mimixbox/internal/applets/shellutils/seq"
	ap_shellutils_serial "github.com/nao1215/mimixbox/internal/applets/shellutils/serial"
	ap_shellutils_sleep "github.com/nao1215/mimixbox/internal/applets/shellutils/sleep"
	ap_shellutils_sort "github.com/nao1215/mimixbox/internal/applets/shellutils/sort"
	ap_shellutils_speaker "github.com/nao1215/mimixbox/internal/applets/shellutils/speaker"
	ap_shellutils_sync "github.com/nao1215/mimixbox/internal/applets/shellutils/sync"
	ap_shellutils_tee "github.com/nao1215/mimixbox/internal/applets/shellutils/tee"
	ap_shellutils_test "github.com/nao1215/mimixbox/internal/applets/shellutils/test"
	ap_shellutils_timecmd "github.com/nao1215/mimixbox/internal/applets/shellutils/timecmd"
	ap_shellutils_timeout "github.com/nao1215/mimixbox/internal/applets/shellutils/timeout"
	ap_shellutils_tree "github.com/nao1215/mimixbox/internal/applets/shellutils/tree"
	ap_shellutils_true "github.com/nao1215/mimixbox/internal/applets/shellutils/true"
	ap_shellutils_tsort "github.com/nao1215/mimixbox/internal/applets/shellutils/tsort"
	ap_shellutils_tty "github.com/nao1215/mimixbox/internal/applets/shellutils/tty"
	ap_shellutils_uname "github.com/nao1215/mimixbox/internal/applets/shellutils/uname"
	ap_shellutils_uniq "github.com/nao1215/mimixbox/internal/applets/shellutils/uniq"
	ap_shellutils_users "github.com/nao1215/mimixbox/internal/applets/shellutils/users"
	ap_shellutils_usleep "github.com/nao1215/mimixbox/internal/applets/shellutils/usleep"
	ap_shellutils_uuidgen "github.com/nao1215/mimixbox/internal/applets/shellutils/uuidgen"
	ap_shellutils_w "github.com/nao1215/mimixbox/internal/applets/shellutils/w"
	ap_shellutils_watch "github.com/nao1215/mimixbox/internal/applets/shellutils/watch"
	ap_shellutils_wget "github.com/nao1215/mimixbox/internal/applets/shellutils/wget"
	ap_shellutils_who "github.com/nao1215/mimixbox/internal/applets/shellutils/who"
	ap_shellutils_whoami "github.com/nao1215/mimixbox/internal/applets/shellutils/whoami"
	ap_shellutils_yes "github.com/nao1215/mimixbox/internal/applets/shellutils/yes"
	ap_textutils_base32 "github.com/nao1215/mimixbox/internal/applets/textutils/base32"
	ap_textutils_cat "github.com/nao1215/mimixbox/internal/applets/textutils/cat"
	ap_textutils_cksum "github.com/nao1215/mimixbox/internal/applets/textutils/cksum"
	ap_textutils_comm "github.com/nao1215/mimixbox/internal/applets/textutils/comm"
	ap_textutils_crc32 "github.com/nao1215/mimixbox/internal/applets/textutils/crc32"
	ap_textutils_dos2unix "github.com/nao1215/mimixbox/internal/applets/textutils/dos2unix"
	ap_textutils_expand "github.com/nao1215/mimixbox/internal/applets/textutils/expand"
	ap_textutils_fmt "github.com/nao1215/mimixbox/internal/applets/textutils/fmt"
	ap_textutils_fold "github.com/nao1215/mimixbox/internal/applets/textutils/fold"
	ap_textutils_head "github.com/nao1215/mimixbox/internal/applets/textutils/head"
	ap_textutils_man "github.com/nao1215/mimixbox/internal/applets/textutils/man"
	ap_textutils_md5sum "github.com/nao1215/mimixbox/internal/applets/textutils/md5sum"
	ap_textutils_nl "github.com/nao1215/mimixbox/internal/applets/textutils/nl"
	ap_textutils_paste "github.com/nao1215/mimixbox/internal/applets/textutils/paste"
	ap_textutils_rev "github.com/nao1215/mimixbox/internal/applets/textutils/rev"
	ap_textutils_sha1sum "github.com/nao1215/mimixbox/internal/applets/textutils/sha1sum"
	ap_textutils_sha256sum "github.com/nao1215/mimixbox/internal/applets/textutils/sha256sum"
	ap_textutils_sha384sum "github.com/nao1215/mimixbox/internal/applets/textutils/sha384sum"
	ap_textutils_sha3sum "github.com/nao1215/mimixbox/internal/applets/textutils/sha3sum"
	ap_textutils_sha512sum "github.com/nao1215/mimixbox/internal/applets/textutils/sha512sum"
	ap_textutils_shuf "github.com/nao1215/mimixbox/internal/applets/textutils/shuf"
	ap_textutils_split "github.com/nao1215/mimixbox/internal/applets/textutils/split"
	ap_textutils_strings "github.com/nao1215/mimixbox/internal/applets/textutils/strings"
	ap_textutils_sum "github.com/nao1215/mimixbox/internal/applets/textutils/sum"
	ap_textutils_tac "github.com/nao1215/mimixbox/internal/applets/textutils/tac"
	ap_textutils_tail "github.com/nao1215/mimixbox/internal/applets/textutils/tail"
	ap_textutils_tr "github.com/nao1215/mimixbox/internal/applets/textutils/tr"
	ap_textutils_unexpand "github.com/nao1215/mimixbox/internal/applets/textutils/unexpand"
	ap_textutils_unix2dos "github.com/nao1215/mimixbox/internal/applets/textutils/unix2dos"
	ap_textutils_uucode "github.com/nao1215/mimixbox/internal/applets/textutils/uucode"
	ap_textutils_wc "github.com/nao1215/mimixbox/internal/applets/textutils/wc"
	ap_textutils_xxd "github.com/nao1215/mimixbox/internal/applets/textutils/xxd"
	ap_util_linux_blkdiscard "github.com/nao1215/mimixbox/internal/applets/util-linux/blkdiscard"
	ap_util_linux_blkid "github.com/nao1215/mimixbox/internal/applets/util-linux/blkid"
	ap_util_linux_blockdev "github.com/nao1215/mimixbox/internal/applets/util-linux/blockdev"
	ap_util_linux_chattr "github.com/nao1215/mimixbox/internal/applets/util-linux/chattr"
	ap_util_linux_chrt "github.com/nao1215/mimixbox/internal/applets/util-linux/chrt"
	ap_util_linux_dmesg "github.com/nao1215/mimixbox/internal/applets/util-linux/dmesg"
	ap_util_linux_eject "github.com/nao1215/mimixbox/internal/applets/util-linux/eject"
	ap_util_linux_fallocate "github.com/nao1215/mimixbox/internal/applets/util-linux/fallocate"
	ap_util_linux_fatattr "github.com/nao1215/mimixbox/internal/applets/util-linux/fatattr"
	ap_util_linux_fbset "github.com/nao1215/mimixbox/internal/applets/util-linux/fbset"
	ap_util_linux_fdflush "github.com/nao1215/mimixbox/internal/applets/util-linux/fdflush"
	ap_util_linux_fdformat "github.com/nao1215/mimixbox/internal/applets/util-linux/fdformat"
	ap_util_linux_fdisk "github.com/nao1215/mimixbox/internal/applets/util-linux/fdisk"
	ap_util_linux_findfs "github.com/nao1215/mimixbox/internal/applets/util-linux/findfs"
	ap_util_linux_flock "github.com/nao1215/mimixbox/internal/applets/util-linux/flock"
	ap_util_linux_freeramdisk "github.com/nao1215/mimixbox/internal/applets/util-linux/freeramdisk"
	ap_util_linux_fsck "github.com/nao1215/mimixbox/internal/applets/util-linux/fsck"
	ap_util_linux_fsck_minix "github.com/nao1215/mimixbox/internal/applets/util-linux/fsck_minix"
	ap_util_linux_fsfreeze "github.com/nao1215/mimixbox/internal/applets/util-linux/fsfreeze"
	ap_util_linux_fstrim "github.com/nao1215/mimixbox/internal/applets/util-linux/fstrim"
	ap_util_linux_getopt "github.com/nao1215/mimixbox/internal/applets/util-linux/getopt"
	ap_util_linux_hexdump "github.com/nao1215/mimixbox/internal/applets/util-linux/hexdump"
	ap_util_linux_hwclock "github.com/nao1215/mimixbox/internal/applets/util-linux/hwclock"
	ap_util_linux_ionice "github.com/nao1215/mimixbox/internal/applets/util-linux/ionice"
	ap_util_linux_ipcrm "github.com/nao1215/mimixbox/internal/applets/util-linux/ipcrm"
	ap_util_linux_ipcs "github.com/nao1215/mimixbox/internal/applets/util-linux/ipcs"
	ap_util_linux_last "github.com/nao1215/mimixbox/internal/applets/util-linux/last"
	ap_util_linux_losetup "github.com/nao1215/mimixbox/internal/applets/util-linux/losetup"
	ap_util_linux_lsattr "github.com/nao1215/mimixbox/internal/applets/util-linux/lsattr"
	ap_util_linux_lsblk "github.com/nao1215/mimixbox/internal/applets/util-linux/lsblk"
	ap_util_linux_lspci "github.com/nao1215/mimixbox/internal/applets/util-linux/lspci"
	ap_util_linux_lsusb "github.com/nao1215/mimixbox/internal/applets/util-linux/lsusb"
	ap_util_linux_mdev "github.com/nao1215/mimixbox/internal/applets/util-linux/mdev"
	ap_util_linux_mesg "github.com/nao1215/mimixbox/internal/applets/util-linux/mesg"
	ap_util_linux_mke2fs "github.com/nao1215/mimixbox/internal/applets/util-linux/mke2fs"
	ap_util_linux_mkfs_minix "github.com/nao1215/mimixbox/internal/applets/util-linux/mkfs_minix"
	ap_util_linux_mkfs_reiser "github.com/nao1215/mimixbox/internal/applets/util-linux/mkfs_reiser"
	ap_util_linux_mkfs_vfat "github.com/nao1215/mimixbox/internal/applets/util-linux/mkfs_vfat"
	ap_util_linux_mkswap "github.com/nao1215/mimixbox/internal/applets/util-linux/mkswap"
	ap_util_linux_mount "github.com/nao1215/mimixbox/internal/applets/util-linux/mount"
	ap_util_linux_nsenter "github.com/nao1215/mimixbox/internal/applets/util-linux/nsenter"
	ap_util_linux_pivot_root "github.com/nao1215/mimixbox/internal/applets/util-linux/pivot_root"
	ap_util_linux_rdate "github.com/nao1215/mimixbox/internal/applets/util-linux/rdate"
	ap_util_linux_rdev "github.com/nao1215/mimixbox/internal/applets/util-linux/rdev"
	ap_util_linux_readprofile "github.com/nao1215/mimixbox/internal/applets/util-linux/readprofile"
	ap_util_linux_renice "github.com/nao1215/mimixbox/internal/applets/util-linux/renice"
	ap_util_linux_rtcwake "github.com/nao1215/mimixbox/internal/applets/util-linux/rtcwake"
	ap_util_linux_script "github.com/nao1215/mimixbox/internal/applets/util-linux/script"
	ap_util_linux_setarch "github.com/nao1215/mimixbox/internal/applets/util-linux/setarch"
	ap_util_linux_setpriv "github.com/nao1215/mimixbox/internal/applets/util-linux/setpriv"
	ap_util_linux_setsid "github.com/nao1215/mimixbox/internal/applets/util-linux/setsid"
	ap_util_linux_swapoff "github.com/nao1215/mimixbox/internal/applets/util-linux/swapoff"
	ap_util_linux_swapon "github.com/nao1215/mimixbox/internal/applets/util-linux/swapon"
	ap_util_linux_switch_root "github.com/nao1215/mimixbox/internal/applets/util-linux/switch_root"
	ap_util_linux_taskset "github.com/nao1215/mimixbox/internal/applets/util-linux/taskset"
	ap_util_linux_tune2fs "github.com/nao1215/mimixbox/internal/applets/util-linux/tune2fs"
	ap_util_linux_uevent "github.com/nao1215/mimixbox/internal/applets/util-linux/uevent"
	ap_util_linux_umount "github.com/nao1215/mimixbox/internal/applets/util-linux/umount"
	ap_util_linux_unshare "github.com/nao1215/mimixbox/internal/applets/util-linux/unshare"
	ap_util_linux_wall "github.com/nao1215/mimixbox/internal/applets/util-linux/wall"
)

// init populates the applet table. Each command is registered under its own
// Name(), so the key can never drift from the command it dispatches to.
func init() {
	Applets = make(map[string]Applet, 316)
	register(ap_archival_ar.New())
	register(ap_archival_bunzip2.New())
	register(ap_archival_compress.New())
	register(ap_archival_cpio.New())
	register(ap_archival_gunzip.New())
	register(ap_archival_gzip.New())
	register(ap_archival_pipeprogress.New())
	register(ap_archival_rpm.New())
	register(ap_archival_rpm2cpio.New())
	register(ap_archival_tar.New())
	register(ap_archival_uncompress.New())
	register(ap_archival_unzip.New())
	register(ap_archival_xzcomp.NewBzcat())
	register(ap_archival_xzcomp.NewLzcat())
	register(ap_archival_xzcomp.NewLzma())
	register(ap_archival_xzcomp.NewUnlzma())
	register(ap_archival_xzcomp.NewUnxz())
	register(ap_archival_xzcomp.NewXz())
	register(ap_archival_xzcomp.NewXzcat())
	register(ap_archival_xzcomp.NewZcat())
	register(ap_archival_zip.New())
	register(ap_compat_bracket.NewBracket())
	register(ap_compat_bracket.NewDoubleBracket())
	register(ap_compat_busybox.New())
	register(ap_compat_cttyhack.New())
	register(ap_compat_shellfront.NewAsh())
	register(ap_compat_shellfront.NewBash())
	register(ap_compat_shellfront.NewHush())
	register(ap_compat_shellfront.NewSh())
	register(ap_compat_unit.New())
	register(ap_console_tools_clear.New())
	register(ap_console_tools_pager.NewLess())
	register(ap_console_tools_pager.NewMore())
	register(ap_console_tools_reset.New())
	register(ap_console_tools_resize.New())
	register(ap_console_tools_stty.New())
	register(ap_debianutils_add_shell.New())
	register(ap_debianutils_ischroot.New())
	register(ap_debianutils_mktemp.New())
	register(ap_debianutils_remove_shell.New())
	register(ap_debianutils_valid_shell.New())
	register(ap_debianutils_which.New())
	register(ap_editors_awk.New())
	register(ap_editors_diff.New())
	register(ap_editors_ed.New())
	register(ap_editors_patch.New())
	register(ap_editors_sed.New())
	register(ap_editors_vi.New())
	register(ap_fileutils_chgrp.New())
	register(ap_fileutils_chown.New())
	register(ap_fileutils_cp.New())
	register(ap_fileutils_link.New())
	register(ap_fileutils_ln.New())
	register(ap_fileutils_ls.New())
	register(ap_fileutils_mkdir.New())
	register(ap_fileutils_mkfifo.New())
	register(ap_fileutils_mountpoint.New())
	register(ap_fileutils_mv.New())
	register(ap_fileutils_readlink.New())
	register(ap_fileutils_rm.New())
	register(ap_fileutils_rmdir.New())
	register(ap_fileutils_shred.New())
	register(ap_fileutils_stat.New())
	register(ap_fileutils_touch.New())
	register(ap_fileutils_truncate.New())
	register(ap_fileutils_unlink.New())
	register(ap_findutils_find.New())
	register(ap_findutils_grep.New())
	register(ap_findutils_grepalias.NewEgrep())
	register(ap_findutils_grepalias.NewFgrep())
	register(ap_findutils_xargs.New())
	register(ap_games_lifegame.New())
	register(ap_jokeutils_banner.New())
	register(ap_jokeutils_cmatrix.New())
	register(ap_jokeutils_cowsay.New())
	register(ap_jokeutils_cowthink.New())
	register(ap_jokeutils_fakemovie.New())
	register(ap_jokeutils_fortune.New())
	register(ap_jokeutils_nyancat.New())
	register(ap_jokeutils_sl.New())
	register(ap_loginutils_acpid.New())
	register(ap_loginutils_addgroup.New())
	register(ap_loginutils_adduser.New())
	register(ap_loginutils_bootchartd.New())
	register(ap_loginutils_chpasswd.New())
	register(ap_loginutils_crond.New())
	register(ap_loginutils_crontab.New())
	register(ap_loginutils_cryptpw.New())
	register(ap_loginutils_delgroup.New())
	register(ap_loginutils_deluser.New())
	register(ap_loginutils_getty.New())
	register(ap_loginutils_init.New())
	register(ap_loginutils_init.NewLinuxrc())
	register(ap_loginutils_login.New())
	register(ap_loginutils_mkpasswd.New())
	register(ap_loginutils_nologin.New())
	register(ap_loginutils_passwd.New())
	register(ap_loginutils_runinit.New())
	register(ap_loginutils_runlevel.New())
	register(ap_loginutils_runparts.New())
	register(ap_loginutils_startstopdaemon.New())
	register(ap_loginutils_su.New())
	register(ap_loginutils_sulogin.New())
	register(ap_loginutils_vlock.New())
	register(ap_netutils_httpstatus.New())
	register(ap_netutils_nc.New())
	register(ap_netutils_ping.New())
	register(ap_netutils_whris.New())
	register(ap_pmutils_halt.NewHalt())
	register(ap_pmutils_halt.NewPoweroff())
	register(ap_pmutils_halt.NewReboot())
	register(ap_procps_fuser.New())
	register(ap_procps_iostat.New())
	register(ap_procps_killall5.New())
	register(ap_procps_klogd.New())
	register(ap_procps_logger.New())
	register(ap_procps_logread.New())
	register(ap_procps_lsof.New())
	register(ap_procps_minips.New())
	register(ap_procps_mpstat.New())
	register(ap_procps_nmeter.New())
	register(ap_procps_pgrep.NewPgrep())
	register(ap_procps_pgrep.NewPkill())
	register(ap_procps_pmap.New())
	register(ap_procps_powertop.New())
	register(ap_procps_ps.New())
	register(ap_procps_pstree.New())
	register(ap_procps_pwdx.New())
	register(ap_procps_smemcap.New())
	register(ap_procps_sysctl.New())
	register(ap_procps_syslogd.New())
	register(ap_procps_top.New())
	register(ap_procps_uptime.New())
	register(ap_procps_vmstat.New())
	register(ap_runit_chpst.New())
	register(ap_runit_envdir.New())
	register(ap_runit_envuidgid.New())
	register(ap_runit_setuidgid.New())
	register(ap_runit_softlimit.New())
	register(ap_runit_svlogd.New())
	register(ap_runit_svok.New())
	register(ap_securityutils_pwcrack.New())
	register(ap_securityutils_pwgen.New())
	register(ap_securityutils_pwscore.New())
	register(ap_securityutils_unshadow.New())
	register(ap_securityutils_zippwcrack.New())
	register(ap_shellutils_arch.New())
	register(ap_shellutils_base64.New())
	register(ap_shellutils_basename.New())
	register(ap_shellutils_bc.New())
	register(ap_shellutils_cal.New())
	register(ap_shellutils_chmod.New())
	register(ap_shellutils_chroot.New())
	register(ap_shellutils_cmp.New())
	register(ap_shellutils_cut.New())
	register(ap_shellutils_date.New())
	register(ap_shellutils_dc.New())
	register(ap_shellutils_dd.New())
	register(ap_shellutils_df.New())
	register(ap_shellutils_dirname.New())
	register(ap_shellutils_du.New())
	register(ap_shellutils_echo.New())
	register(ap_shellutils_env.New())
	register(ap_shellutils_expr.New())
	register(ap_shellutils_factor.New())
	register(ap_shellutils_false.New())
	register(ap_shellutils_free.New())
	register(ap_shellutils_fsync.New())
	register(ap_shellutils_ghrdc.New())
	register(ap_shellutils_groups.New())
	register(ap_shellutils_hostid.New())
	register(ap_shellutils_hostname.New())
	register(ap_shellutils_id.New())
	register(ap_shellutils_install.New())
	register(ap_shellutils_kill.New())
	register(ap_shellutils_killall.New())
	register(ap_shellutils_logcollect.New())
	register(ap_shellutils_logname.New())
	register(ap_shellutils_mbsh.New())
	register(ap_shellutils_mknod.New())
	register(ap_shellutils_nice.New())
	register(ap_shellutils_nohup.New())
	register(ap_shellutils_nproc.New())
	register(ap_shellutils_od.New())
	register(ap_shellutils_path.New())
	register(ap_shellutils_pidof.New())
	register(ap_shellutils_posixer.New())
	register(ap_shellutils_printenv.New())
	register(ap_shellutils_printf.New())
	register(ap_shellutils_pwd.New())
	register(ap_shellutils_realpath.New())
	register(ap_shellutils_sddf.New())
	register(ap_shellutils_seq.New())
	register(ap_shellutils_serial.New())
	register(ap_shellutils_sleep.New())
	register(ap_shellutils_sort.New())
	register(ap_shellutils_speaker.New())
	register(ap_shellutils_sync.New())
	register(ap_shellutils_tee.New())
	register(ap_shellutils_test.New())
	register(ap_shellutils_timecmd.New())
	register(ap_shellutils_timeout.New())
	register(ap_shellutils_tree.New())
	register(ap_shellutils_true.New())
	register(ap_shellutils_tsort.New())
	register(ap_shellutils_tty.New())
	register(ap_shellutils_uname.New())
	register(ap_shellutils_uniq.New())
	register(ap_shellutils_users.New())
	register(ap_shellutils_usleep.New())
	register(ap_shellutils_uuidgen.New())
	register(ap_shellutils_w.New())
	register(ap_shellutils_watch.New())
	register(ap_shellutils_wget.New())
	register(ap_shellutils_who.New())
	register(ap_shellutils_whoami.New())
	register(ap_shellutils_yes.New())
	register(ap_textutils_base32.New())
	register(ap_textutils_cat.New())
	register(ap_textutils_cksum.New())
	register(ap_textutils_comm.New())
	register(ap_textutils_crc32.New())
	register(ap_textutils_dos2unix.New())
	register(ap_textutils_expand.New())
	register(ap_textutils_fmt.New())
	register(ap_textutils_fold.New())
	register(ap_textutils_head.New())
	register(ap_textutils_man.New())
	register(ap_textutils_md5sum.New())
	register(ap_textutils_nl.New())
	register(ap_textutils_paste.New())
	register(ap_textutils_rev.New())
	register(ap_textutils_sha1sum.New())
	register(ap_textutils_sha256sum.New())
	register(ap_textutils_sha384sum.New())
	register(ap_textutils_sha3sum.New())
	register(ap_textutils_sha512sum.New())
	register(ap_textutils_shuf.New())
	register(ap_textutils_split.New())
	register(ap_textutils_strings.New())
	register(ap_textutils_sum.New())
	register(ap_textutils_tac.New())
	register(ap_textutils_tail.New())
	register(ap_textutils_tr.New())
	register(ap_textutils_unexpand.New())
	register(ap_textutils_unix2dos.New())
	register(ap_textutils_uucode.NewUudecode())
	register(ap_textutils_uucode.NewUuencode())
	register(ap_textutils_wc.New())
	register(ap_textutils_xxd.New())
	register(ap_util_linux_blkdiscard.New())
	register(ap_util_linux_blkid.New())
	register(ap_util_linux_blockdev.New())
	register(ap_util_linux_chattr.New())
	register(ap_util_linux_chrt.New())
	register(ap_util_linux_dmesg.New())
	register(ap_util_linux_eject.New())
	register(ap_util_linux_fallocate.New())
	register(ap_util_linux_fatattr.New())
	register(ap_util_linux_fbset.New())
	register(ap_util_linux_fdflush.New())
	register(ap_util_linux_fdformat.New())
	register(ap_util_linux_fdisk.New())
	register(ap_util_linux_findfs.New())
	register(ap_util_linux_flock.New())
	register(ap_util_linux_freeramdisk.New())
	register(ap_util_linux_fsck.New())
	register(ap_util_linux_fsck_minix.New())
	register(ap_util_linux_fsfreeze.New())
	register(ap_util_linux_fstrim.New())
	register(ap_util_linux_getopt.New())
	register(ap_util_linux_hexdump.NewHd())
	register(ap_util_linux_hexdump.NewHexdump())
	register(ap_util_linux_hwclock.New())
	register(ap_util_linux_ionice.New())
	register(ap_util_linux_ipcrm.New())
	register(ap_util_linux_ipcs.New())
	register(ap_util_linux_last.New())
	register(ap_util_linux_losetup.New())
	register(ap_util_linux_lsattr.New())
	register(ap_util_linux_lsblk.New())
	register(ap_util_linux_lspci.New())
	register(ap_util_linux_lsusb.New())
	register(ap_util_linux_mdev.New())
	register(ap_util_linux_mesg.New())
	register(ap_util_linux_mke2fs.New())
	register(ap_util_linux_mke2fs.NewMkfsExt2())
	register(ap_util_linux_mkfs_minix.New())
	register(ap_util_linux_mkfs_reiser.New())
	register(ap_util_linux_mkfs_vfat.New())
	register(ap_util_linux_mkfs_vfat.NewMkdosfs())
	register(ap_util_linux_mkswap.New())
	register(ap_util_linux_mount.New())
	register(ap_util_linux_nsenter.New())
	register(ap_util_linux_pivot_root.New())
	register(ap_util_linux_rdate.New())
	register(ap_util_linux_rdev.New())
	register(ap_util_linux_readprofile.New())
	register(ap_util_linux_renice.New())
	register(ap_util_linux_rtcwake.New())
	register(ap_util_linux_script.NewScript())
	register(ap_util_linux_script.NewScriptreplay())
	register(ap_util_linux_setarch.NewLinux32())
	register(ap_util_linux_setarch.NewLinux64())
	register(ap_util_linux_setarch.NewSetarch())
	register(ap_util_linux_setpriv.New())
	register(ap_util_linux_setsid.New())
	register(ap_util_linux_swapoff.New())
	register(ap_util_linux_swapon.New())
	register(ap_util_linux_switch_root.New())
	register(ap_util_linux_taskset.New())
	register(ap_util_linux_tune2fs.New())
	register(ap_util_linux_uevent.New())
	register(ap_util_linux_umount.New())
	register(ap_util_linux_unshare.New())
	register(ap_util_linux_wall.New())
}
