package main

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// demoTapePath is the VHS script that renders assets/demo.gif, the first thing
// a reader sees in README.md.
const demoTapePath = "../../assets/demo.tape"

// readmePath is the file that embeds the rendered GIF.
const readmePath = "../../README.md"

// TestDemoTapeCommandsStillWork runs every shell line the demo tape types and
// requires each to exit 0.
//
// A GIF cannot be regenerated byte-for-byte (VHS output varies with timing,
// fonts and the encoder), so CI cannot diff it to prove the demo is current.
// What can be checked deterministically is the thing that actually rots: the
// command lines inside the tape. Drop an applet or change a flag and this test
// fails here, instead of the next `make demo` quietly recording a terminal full
// of usage errors -- `vhs` itself exits 0 no matter what appears on screen.
//
// The lines are pipelines (`mimixbox --list | head -n 4`), so they run through
// bash exactly as the tape's `Set Shell bash` does, with a freshly built
// mimixbox first on PATH just like the tape's documented regeneration command.
func TestDemoTapeCommandsStillWork(t *testing.T) {
	t.Parallel()

	commands := mimixboxCommandsInTape(t, demoTapePath)
	if len(commands) == 0 {
		t.Fatalf("%s types no mimixbox commands; the tape or this parser is wrong", demoTapePath)
	}

	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash not available; the tape declares `Set Shell bash`")
	}
	binDir := buildMimixboxForTape(t)

	for _, command := range commands {
		t.Run(command, func(t *testing.T) {
			t.Parallel()

			// -o pipefail: without it `mimixbox --list | head -n 4` reports
			// head's status, so a broken applet at the head of a pipeline would
			// pass here. The tape's own shell does not set it -- that is the
			// point, since a demo whose first command errors still renders a
			// clean-looking GIF.
			cmd := exec.CommandContext(t.Context(), bash, "-o", "pipefail", "-c", command)
			// A per-scenario workdir keeps a stray applet write out of the
			// repository, and the staged binary shadows any host mimixbox.
			cmd.Dir = t.TempDir()
			cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

			out, err := cmd.CombinedOutput()
			if err != nil && !isSIGPIPE(err) {
				t.Errorf("%q failed: %v\noutput: %s", command, err, out)
			}
		})
	}
}

// sigpipeStatus is what bash reports for a command killed by SIGPIPE.
const sigpipeStatus = 141

// isSIGPIPE reports whether a pipeline failed only because its producer was
// killed once the consumer had taken what it wanted.
//
// `mimixbox --list | head -n 4` is exactly that: --list writes one line per
// applet, head closes the pipe after four, and whether the remaining ~26KB is
// still in flight at that moment is a race. Under pipefail that surfaces as
// exit 141 on a run that is behaving correctly, so treating it as a failure
// would make this test flaky rather than strict. Every other nonzero status --
// including the exit 1 a renamed applet produces, which is what this test
// exists to catch -- is still a failure.
func isSIGPIPE(err error) bool {
	var exit *exec.ExitError
	return errors.As(err, &exit) && exit.ExitCode() == sigpipeStatus
}

// buildMimixboxForTape builds the multi-call binary from this package and
// returns the directory holding it.
func buildMimixboxForTape(t *testing.T) string {
	t.Helper()

	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("go toolchain not available; cannot build the binary the tape drives")
	}
	pkgDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	binDir := t.TempDir()
	build := exec.CommandContext(context.Background(), goBin, "build", "-o", filepath.Join(binDir, "mimixbox"), ".")
	build.Dir = pkgDir
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
	return binDir
}

// mimixboxCommandsInTape returns the mimixbox command lines a VHS tape types.
// VHS keeps typed text in `Type "..."` directives; everything else in the file
// (Output, Set, Sleep) is not a shell command. Lines typed as shell comments
// are narration for the viewer, not commands worth asserting on.
func mimixboxCommandsInTape(t *testing.T, path string) []string {
	t.Helper()

	data, err := os.ReadFile(path) //nolint:gosec // a test-supplied path inside the repository
	if err != nil {
		t.Fatal(err)
	}

	var commands []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, `Type "`) || !strings.HasSuffix(line, `"`) {
			continue
		}
		typed := strings.TrimSuffix(strings.TrimPrefix(line, `Type "`), `"`)
		// VHS unescapes the double-quoted argument before typing it, so a tape
		// that wants the shell to see \n writes \\n.
		typed = strings.ReplaceAll(typed, `\\`, `\`)
		if strings.HasPrefix(typed, "#") || !strings.Contains(typed, "mimixbox") {
			continue
		}
		commands = append(commands, typed)
	}
	return commands
}

// TestDemoTapeRendersTheReadmeGIF pins the output path the tape writes. README
// embeds assets/demo.gif; a tape that renders somewhere else leaves the README
// showing a stale image with nothing failing.
func TestDemoTapeRendersTheReadmeGIF(t *testing.T) {
	t.Parallel()

	tape, err := os.ReadFile(demoTapePath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(tape), `Output "assets/demo.gif"`) {
		t.Errorf("%s does not render assets/demo.gif", demoTapePath)
	}

	readme, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(readme), "./assets/demo.gif") {
		t.Errorf("%s no longer embeds ./assets/demo.gif; the tape renders it for nobody", readmePath)
	}
}
